[server]
maxUploadSize = 1000
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#1772B1"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#2D2D2D"
textColor = "#FFFFFF"
